{
 "title": "Aggregations",
 "time": { "from": "2014-04-26T13:15:29.676Z", "to": "2018-01-05T19:58:44.276Z" },
 "panels": [
  {
   "title": "Hourly Aggregations Max",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Berlin\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Berlin' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Dresden\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Dresden' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Hamm\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Hamm' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Munich\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Munich' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Rostock\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Rostock' LIMIT 100000 "
    }
   ]
  },
  {
   "title": "Hourly Aggregations Events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Berlin\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Berlin' LIMIT 1000000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Dresden\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Dresden' LIMIT 1000000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Hamm\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Hamm' LIMIT 1000000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT event_count AS \"Munich\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Munich' LIMIT 1000000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT event_count AS \"Rostock\", \"timestamp\" FROM hourly_aggregations WHERE __key = 'Rostock' LIMIT 1000000 "
    }
   ]
  },
  {
   "title": "Daily Aggregations Max",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Berlin\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Berlin' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Dresden\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Dresden' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Hamm\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Hamm' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Munich\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Munich' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Rostock\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Rostock' LIMIT 100000 "
    }
   ]
  },
  {
   "title": "Daily Aggregations Events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Berlin\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Berlin' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Dresden\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Dresden' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Hamm\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Hamm' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count AS \"Munich\", \"timestamp\" FROM daily_aggregations WHERE __key = 'Munich' LIMIT 100000 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, event_count, \"timestamp\" FROM daily_aggregations WHERE __key = 'Rostock' LIMIT 100000 "
    }
   ]
  },
  {
   "title": "Weekly Aggregations Max",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Berlin\", \"timestamp\" FROM weekly_aggregations WHERE __key = 'Berlin' LIMIT 50 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Dresden\", \"timestamp\" FROM weekly_aggregations WHERE __key = 'Dresden' LIMIT 50 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Hamm\", \"timestamp\" FROM weekly_aggregations WHERE __key = 'Hamm' LIMIT 50 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Munich\", \"timestamp\" FROM weekly_aggregations WHERE __key = 'Munich' LIMIT 50 "
    },
    {
     "dataset": "data",
     "rawSql": "SELECT __key, max_actual_pv AS \"Rostock\", \"timestamp\" FROM weekly_aggregations WHERE __key = 'Rostock' LIMIT 50 "
    }
   ]
  }
 ]
}