apiVersion: 1

datasources:
  - name: Database
    uid: dfhdh4hw50um8a
    type: postgres
    url: database:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: true
    editable: true
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
