name: build-latest
on:
  push:
    branches:
      - '**'
      - '!main'

env:
  registry: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: [kafka-admin, produce, setup]
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ github.repository }}
      - run: docker build -t ${{ env.registry }}/${{ github.repository }}/${{ matrix.image }}:latest -f dockerfiles/${{ matrix.image }}/Dockerfile dockerfiles/${{ matrix.image }}
      - run: docker push ${{ env.registry }}/${{ github.repository }}/${{ matrix.image }}:latest