name: build-latest
on:
  push:
    branches:
      - '**'
      - '!main'

env:
  registry: ghcr.io

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ github.repository }}
      - run: docker build -t ${{ env.registry }}/${{ github.repository }}/${{ github.job }}:latest -f dockerfiles/${{ github.job }}/Dockerfile dockerfiles/${{ github.job }}
      - run: docker push ${{ env.registry }}/${{ github.repository }}/${{ github.job }}:latest